globalVariables(c(
  ".",
  "ADT",
  "AVALC",
  "ADT.join",
  "AVALC",
  "AVALC.join",
  "PARAMCD",
  "STUDYID",
  "temp_rs",
  "tmp_obs",
  "tmp_obs_nr_filter_confirmation",
  "tmp_obs_nr_filter_confirmation.join",
  "tmp_order",
  "TRTSDT",
  "USUBJID",
  "temp_date",
  "AVALC"
))
