---
name: Check Templates

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

jobs:
  templates:
    name: Check Templates
    uses: pharmaverse/admiralci/.github/workflows/check-templates.yml@main
    secrets: inherit
    with:
      r-version: "4.1"
      push-templates-data: true
      exclude-templates-data: "adrs_basic"
